### ISSUE TITLE
Can the app-root tabView be addressed in javascript?

### ISSUE THREAD

**Issue by tcrgit** [NativeScript/template-tab-navigation#60]
I added an id="tabViewContainer" to the <TabView ...> xml tag in app-root.xml, but I am unable to figure out how to address the TabView in javascript. 

The reason I ask is that I would like to have the javascript navigate to the home tab after the user finishes data-entry in my app's dataEntry tab. 

Edit: I eventually worked around it with ``` args.object.page.frame.parent.parent.selectedIndex = 0``` but that is an ugly way to get to the root TabView container.

**Comment by tsonevn** [comment]
Hi @tcrgit,
You can try to set up an id to the frame and to access it by using `getFrameById`. You can check the example [here](https://docs.nativescript.org/ui/basics#set-the-bindingcontext-while-navigating-to-a-page), where it is described how to use this method. After you get the needed frame you should again use `parent` property to get the root TabView component as follows:
```
let  tabView = frame.parent.parent;
tabView.selectedIndex = 0;
```

**Comment by manoldonev** [comment]
You can use the [getRootView()](https://docs.nativescript.org/api-reference/modules/_application_#getrootview) method of the application module.

See https://github.com/NativeScript/template-drawer-navigation/blob/2e05d4af829bd9e6e1d2ed493076bef1fb9e1ce7/home/home-page.js#L11 for sample usage.
